var annotated_dup =
[
    [ "AirCraft", "class_air_craft.html", "class_air_craft" ],
    [ "AircraftUnit", "class_aircraft_unit.html", "class_aircraft_unit" ],
    [ "Barracks", "class_barracks.html", "class_barracks" ],
    [ "Buggy", "class_buggy.html", "class_buggy" ],
    [ "Building", "class_building.html", "class_building" ],
    [ "Bullet", "class_bullet.html", "class_bullet" ],
    [ "Button", "struct_button.html", "struct_button" ],
    [ "Firehawk", "class_firehawk.html", "class_firehawk" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "Global", "struct_global.html", null ],
    [ "GUI", "class_g_u_i.html", "class_g_u_i" ],
    [ "HammerHead", "class_hammer_head.html", "class_hammer_head" ],
    [ "Harvester", "class_harvester.html", "class_harvester" ],
    [ "Headquarters", "class_headquarters.html", "class_headquarters" ],
    [ "InfantryUnit", "class_infantry_unit.html", "class_infantry_unit" ],
    [ "LevelEditor", "class_level_editor.html", "class_level_editor" ],
    [ "LevelLoader", "class_level_loader.html", "class_level_loader" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "Missile", "class_missile.html", "class_missile" ],
    [ "NeuralNetworks", "class_neural_networks.html", "class_neural_networks" ],
    [ "Particle", "struct_particle.html", "struct_particle" ],
    [ "ParticleSystem", "class_particle_system.html", "class_particle_system" ],
    [ "Refinery", "class_refinery.html", "class_refinery" ],
    [ "RiflemanSquad", "class_rifleman_squad.html", "class_rifleman_squad" ],
    [ "SideBar", "class_side_bar.html", "class_side_bar" ],
    [ "SoundManager", "class_sound_manager.html", "class_sound_manager" ],
    [ "TankAurora", "class_tank_aurora.html", "class_tank_aurora" ],
    [ "Tile", "class_tile.html", "class_tile" ],
    [ "TrailPart", "struct_trail_part.html", "struct_trail_part" ],
    [ "Unit", "class_unit.html", "class_unit" ],
    [ "VehicleUnit", "class_vehicle_unit.html", "class_vehicle_unit" ],
    [ "WarFactory", "class_war_factory.html", "class_war_factory" ]
];